create table COCKTAIL_SHOPPING_LIST
(
    COCKTAIL_ID UUID NOT NULL,
    SHOPPING_LIST_ID UUID NOT NULL
);

CREATE INDEX COCKTAIL_SHOPPING_LIST_COCKTAIL_ID_IDX ON COCKTAIL_SHOPPING_LIST (COCKTAIL_ID);
ALTER TABLE IF EXISTS COCKTAIL_SHOPPING_LIST ADD FOREIGN KEY (COCKTAIL_ID) REFERENCES COCKTAIL(ID);

CREATE INDEX COCKTAIL_SHOPPING_LIST_SHOP_LIST_ID_IDX ON COCKTAIL_SHOPPING_LIST (SHOPPING_LIST_ID);
ALTER TABLE IF EXISTS COCKTAIL_SHOPPING_LIST ADD FOREIGN KEY (SHOPPING_LIST_ID) REFERENCES SHOPPING_LIST(ID);
