ALTER TABLE COCKTAIL ADD COLUMN glass VARCHAR(255) DEFAULT NULL;
ALTER TABLE COCKTAIL ADD COLUMN instructions VARCHAR(255) DEFAULT NULL;
ALTER TABLE COCKTAIL ADD COLUMN image_url VARCHAR(255) DEFAULT NULL;